### ISSUE TITLE
how can I call cgal in my dll

### ISSUE THREAD

**Issue by chuzhu** [Michsior14/amazonlinux-occt-cgal-node#2]
Thanks for your dockerfile, But I still have two questions:

1.I build it and got four images, which one should I use?
![1](https://user-images.githubusercontent.com/13775164/165895663-e5572da4-724b-4aec-a531-d954ff83de9d.png)

2. I used the first image , but how can I load cgal header files in my dll? should I make some configuration ？

I am looking forward to hearing from you soon. Thanks.

**Comment by Michsior14** [comment]
Hey ;)

1. Just tag your image during the building so you can distinguish between them (https://docs.docker.com/develop/develop-images/multistage-build/)
2. The packages are output in /opt/conda, so you need to tel the linker to look for those there. Additionally you probably will need to set `LD_PRELOAD: /opt/conda/lib/libstdc++.so` because AM 2 has to old gcc++ installed by default.
